# ===============================
# Browser Configuration
# ===============================
browser=chrome

# ===============================
# Application URL
# ===============================
url=https://www.amazon.in/

# ===============================
# Wait Configuration
# ===============================
implicitWait=10
explicitWait=20
pageLoadTimeout=30

# ===============================
# Screenshot Path
# ===============================
screenshotPath=screenshots/

# ===============================
# Report Path
# ===============================
reportPath=reports/ExtentReport.html

# ===============================
# Test Data
# ===============================
iphoneSearch=iPhone
galaxySearch=Samsung Galaxy